# Generated by Django 5.1.15 on 2026-05-11 05:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('name_th', models.CharField(blank=True, default='', max_length=120)),
                ('color', models.CharField(default='#00B14F', max_length=16)),
                ('order', models.IntegerField(default=0)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('last_visit', models.CharField(blank=True, default='', max_length=32)),
                ('color', models.CharField(default='#94A3B8', max_length=16)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParkedOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('items', models.JSONField(default=list)),
                ('customer_id', models.UUIDField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.CharField(default='shop', max_length=32, primary_key=True, serialize=False)),
                ('shop_name', models.CharField(default='Brave POS', max_length=200)),
                ('business_type', models.CharField(default='Restaurant', max_length=64)),
                ('tax_id', models.CharField(blank=True, default='', max_length=64)),
                ('pos_id', models.CharField(default='001', max_length=64)),
                ('branch', models.CharField(default='Main', max_length=120)),
                ('pos_number', models.CharField(default='001', max_length=16)),
                ('open_time', models.CharField(default='09:00', max_length=8)),
                ('close_time', models.CharField(default='22:00', max_length=8)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=7, max_digits=5)),
                ('tax_mode', models.CharField(default='exclusive', max_length=16)),
                ('service_charge_enabled', models.BooleanField(default=False)),
                ('service_charge_percent', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('logo_url', models.TextField(blank=True, default='')),
                ('logo_path', models.TextField(blank=True, default='')),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('beam_merchant_id', models.CharField(blank=True, default='', max_length=128)),
                ('beam_api_key', models.CharField(blank=True, default='', max_length=256)),
                ('beam_sandbox', models.BooleanField(default=True)),
                ('printer_enabled', models.BooleanField(default=False)),
                ('printer_transport', models.CharField(default='disabled', max_length=16)),
                ('printer_address', models.CharField(blank=True, default='', max_length=200)),
                ('printer_paper_width', models.IntegerField(default=80)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_number', models.IntegerField(default=1)),
                ('start_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('opened_by', models.CharField(default='Admin', max_length=120)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.CharField(blank=True, default='', max_length=120)),
                ('total_sales_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_paid_in', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_paid_out', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_in_drawer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_in_drawer', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=16)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_type', models.CharField(default='none', max_length=16)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_method', models.CharField(blank=True, default='', max_length=64)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('change', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('new', 'New'), ('preparing', 'Preparing'), ('completed', 'Completed'), ('cancel', 'Cancelled')], default='completed', max_length=16)),
                ('source', models.CharField(choices=[('table', 'Table'), ('delivery', 'Delivery'), ('kiosk', 'KIOSK'), ('other', 'Other')], default='table', max_length=16)),
                ('customer_name', models.CharField(blank=True, default='', max_length=200)),
                ('beam_charge_id', models.CharField(blank=True, default='', max_length=128)),
                ('delivery_provider', models.CharField(blank=True, default='', max_length=64)),
                ('delivery_status', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_time', models.CharField(blank=True, default='', max_length=8)),
                ('staff', models.CharField(blank=True, default='', max_length=120)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='bravepos.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('name_th', models.CharField(blank=True, default='', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('sku', models.CharField(blank=True, default='', max_length=64)),
                ('barcode', models.CharField(blank=True, default='', max_length=64)),
                ('image_url', models.TextField(blank=True, default='')),
                ('image_base64', models.TextField(blank=True, default='')),
                ('is_favorite', models.BooleanField(default=False)),
                ('tax_type', models.CharField(default='V', max_length=4)),
                ('product_type', models.CharField(default='P', max_length=4)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='bravepos.category')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.IntegerField(default=1)),
                ('category_id', models.UUIDField(blank=True, null=True)),
                ('category_name', models.CharField(blank=True, default='', max_length=120)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bravepos.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='bravepos.product')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('paid_in', 'Paid In'), ('paid_out', 'Paid Out')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='bravepos.shift')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, default='', max_length=200)),
                ('type', models.CharField(choices=[('in', 'Stock in'), ('out', 'Stock out'), ('adjust', 'Adjust'), ('check', 'Check')], max_length=16)),
                ('qty', models.IntegerField()),
                ('note', models.TextField(blank=True, default='')),
                ('document_no', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='bravepos.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['source'], name='bravepos_or_source_384e50_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='bravepos_or_status_951101_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='bravepos_pr_categor_63a2ef_idx'),
        ),
    ]
