# Generated by Django 4.2.30 on 2026-05-12 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bravepos', '0003_staff_branchsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='bravepos.branch'),
        ),
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='bravepos.branch'),
        ),
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bravepos.branch'),
        ),
        migrations.AddField(
            model_name='parkedorder',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parked_orders', to='bravepos.branch'),
        ),
        migrations.AddField(
            model_name='product',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='bravepos.branch'),
        ),
        migrations.AddField(
            model_name='shift',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='bravepos.branch'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='bravepos.branch'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['branch'], name='bravepos_ca_branch__233387_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['branch'], name='bravepos_cu_branch__5f4af9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['branch'], name='bravepos_or_branch__bd1beb_idx'),
        ),
        migrations.AddIndex(
            model_name='parkedorder',
            index=models.Index(fields=['branch'], name='bravepos_pa_branch__dd08de_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['branch'], name='bravepos_pr_branch__4652a8_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['branch'], name='bravepos_sh_branch__fb1cd0_idx'),
        ),
    ]
