# Generated by Django 4.2.30 on 2026-06-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bravepos', '0005_backfill_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='logo_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
