# Generated by Django 4.2.30 on 2026-06-08 10:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("bravepos", "0009_staff_pin"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeakClientToken",
            fields=[
                (
                    "id",
                    models.CharField(
                        default="default",
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(max_length=512)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="peak_queue_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="order",
            name="peak_response",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="tax_invoice_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PeakRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.TextField()),
                ("method", models.CharField(max_length=8)),
                ("headers", models.JSONField(blank=True, null=True)),
                ("body", models.JSONField(blank=True, null=True)),
                ("response", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="bravepos_pe_created_eb40ae_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PeakProductMap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("peak_code", models.CharField(db_index=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peak_map",
                        to="bravepos.product",
                    ),
                ),
            ],
        ),
    ]
