# Generated by Django 4.2.30 on 2026-06-09 12:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


# Default Paid In / Paid Out reason codes (Thai), seeded once per existing
# branch.  Admins can rename / reorder / delete them afterwards in Settings.
DEFAULT_PAID_IN = ["ค่าบริการ", "ค่าดอกเบี้ยเงินฝาก", "ค่าขายสินค้า", "โบนัส", "อื่นๆ"]
DEFAULT_PAID_OUT = [
    "จ่ายเงินเดือน", "จ่ายค่าสาธารณูปโภค", "ซื้อของเข้า",
    "อื่นๆ", "ค่าตกแต่ง", "ค่าพาหนะ",
]


def seed_categories(apps, schema_editor):
    Branch = apps.get_model("bravepos", "Branch")
    DrawerCategory = apps.get_model("bravepos", "DrawerCategory")
    rows = []
    for branch in Branch.objects.all():
        for kind, names in (("paid_in", DEFAULT_PAID_IN), ("paid_out", DEFAULT_PAID_OUT)):
            for i, name in enumerate(names):
                rows.append(DrawerCategory(
                    branch=branch, type=kind, name=name, name_th=name, sort_order=i,
                ))
    DrawerCategory.objects.bulk_create(rows)


def unseed_categories(apps, schema_editor):
    apps.get_model("bravepos", "DrawerCategory").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bravepos', '0010_peakclienttoken_order_peak_queue_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftmovement',
            name='category',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.CreateModel(
            name='DrawerCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('paid_in', 'Paid In'), ('paid_out', 'Paid Out')], max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('name_th', models.CharField(blank=True, default='', max_length=120)),
                ('sort_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drawer_categories', to='bravepos.branch')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['branch', 'type'], name='bravepos_dr_branch__207a68_idx')],
            },
        ),
        migrations.RunPython(seed_categories, unseed_categories),
    ]
