# Generated by Django 4.2.30 on 2026-06-09 12:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bravepos', '0011_drawer_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('in', 'Stock in'), ('out', 'Stock out')], max_length=4)),
                ('document_no', models.CharField(db_index=True, max_length=64)),
                ('ref_no', models.CharField(blank=True, default='', max_length=120)),
                ('vendor', models.CharField(blank=True, default='', max_length=200)),
                ('receiver', models.CharField(blank=True, default='', max_length=200)),
                ('note', models.TextField(blank=True, default='')),
                ('tax_included', models.BooleanField(default=False)),
                ('avg_cost', models.BooleanField(default=False)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_by', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_documents', to='bravepos.branch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockDocumentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barcode', models.CharField(blank=True, default='', max_length=64)),
                ('product_name', models.CharField(blank=True, default='', max_length=200)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bravepos.stockdocument')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_document_items', to='bravepos.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='stockdocument',
            index=models.Index(fields=['branch', 'type', '-created_at'], name='bravepos_st_branch__d4fa00_idx'),
        ),
    ]
