# Generated by Django 4.2.30 on 2026-06-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bravepos', '0012_stockdocument_stockdocumentitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdocument',
            name='adjust_type',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='stockdocument',
            name='document_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='stockdocument',
            name='type',
            field=models.CharField(choices=[('in', 'Stock in'), ('out', 'Stock out'), ('adjust', 'Adjust stock'), ('check', 'Check stock')], max_length=8),
        ),
    ]
