# Generated by Django 4.2.30 on 2026-06-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bravepos', '0013_stockdocument_adjust_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='voided_by',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
