# Generated by Django 4.2.30 on 2026-06-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bravepos', '0015_orderitem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdocumentitem',
            name='before_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stockdocumentitem',
            name='reconcile_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
