# Generated by Django 4.2.30 on 2026-06-11 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bravepos", "0017_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="bravepos.unit",
            ),
        ),
    ]
