# Generated by Django 4.2.30 on 2026-06-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bravepos", "0018_product_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="close_time",
            field=models.CharField(default="22:00", max_length=8),
        ),
        migrations.AddField(
            model_name="branch",
            name="open_time",
            field=models.CharField(default="09:00", max_length=8),
        ),
    ]
