# Generated by Django 4.2.30 on 2026-06-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bravepos", "0019_branch_close_time_branch_open_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="peak_account_code",
            field=models.CharField(blank=True, default="BSV003", max_length=32),
        ),
    ]
