# Generated by Django 4.2.30 on 2026-06-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bravepos", "0020_branch_peak_account_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="omise_charge_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="order",
            name="omise_link_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="order",
            name="processing_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="order",
            name="processing_fee_vat",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="order",
            name="vat_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="settings",
            name="omise_fee_percent",
            field=models.DecimalField(decimal_places=2, default=3.65, max_digits=5),
        ),
        migrations.AddField(
            model_name="settings",
            name="omise_public_key",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="settings",
            name="omise_secret_key",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
