# Generated by Django 4.2.30 on 2026-06-18 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bravepos", "0021_order_omise_charge_id_order_omise_link_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branchsession",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="bravepos.branch",
            ),
        ),
    ]
