# Generated by Django 4.2.30 on 2026-06-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bravepos', '0022_alter_branchsession_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='beam_link_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='settings',
            name='beam_card_fee_percent',
            field=models.DecimalField(decimal_places=2, default=3.65, max_digits=5),
        ),
    ]
