# Generated by Django 4.2.30 on 2026-07-14 05:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("bravepos", "0023_order_beam_link_id_settings_beam_card_fee_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="queue_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="bravepos.shift",
            ),
        ),
        migrations.CreateModel(
            name="SelfOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("items", models.JSONField(default=list)),
                (
                    "goods_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "vat_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "processing_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "processing_fee_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "payment_method",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "beam_charge_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "beam_link_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("qr_image_cache", models.TextField(blank=True, default="")),
                ("payment_uri_cache", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("print_claimed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "print_claimed_by",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("printed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="self_orders",
                        to="bravepos.branch",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="self_order",
                        to="bravepos.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["branch", "status"],
                        name="bravepos_se_branch__eff33b_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="bravepos_se_status_e7cb5e_idx",
                    ),
                ],
            },
        ),
    ]
