# Generated by Django 4.2.30 on 2026-07-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bravepos", "0024_order_queue_number_order_shift_selforder"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="beam_api_key",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="branch",
            name="beam_card_fee_percent",
            field=models.DecimalField(decimal_places=2, default=3.65, max_digits=5),
        ),
        migrations.AddField(
            model_name="branch",
            name="beam_merchant_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="branch",
            name="beam_sandbox",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="omise_fee_percent",
            field=models.DecimalField(decimal_places=2, default=3.65, max_digits=5),
        ),
        migrations.AddField(
            model_name="branch",
            name="omise_public_key",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="branch",
            name="omise_secret_key",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="branch",
            name="payment_own",
            field=models.BooleanField(default=False),
        ),
    ]
