# Generated by Django 4.2.30 on 2026-07-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bravepos', '0025_branch_beam_api_key_branch_beam_card_fee_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='self_order_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
