# Generated by Django 4.2.30 on 2026-07-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bravepos", "0029_branch_owns_payment_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="customer",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="customer",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("unspecified", "Unspecified"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="group",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="customer",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="customer",
            name="tax_branch",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="customer",
            name="tax_id",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="order",
            name="pos_tax_invoice",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
