# Generated by Django 6.0.7 on 2026-08-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bravepos", "0030_pos_full_tax_invoice"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["branch", "-created_at"], name="bravepos_or_branch__fcd171_idx"
            ),
        ),
    ]
