# Generated by Django 4.2.30 on 2026-08-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bravepos", "0031_order_bravepos_or_branch__fcd171_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="par_level",
            field=models.IntegerField(default=0),
        ),
    ]
