# Generated by Django 4.2.30 on 2026-08-11 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bravepos', '0031_consolidatedreceipt'),
        ('bravepos', '0032_product_par_level'),
    ]

    operations = [
    ]
