# Generated by Django 4.2.30 on 2026-08-28 03:43

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("bravepos", "0040_stock_out_reason_codes"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppRelease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.CharField(max_length=32)),
                ("version_code", models.PositiveIntegerField(db_index=True, default=0)),
                ("build_id", models.CharField(blank=True, default="", max_length=64)),
                ("drive_file_id", models.CharField(max_length=128)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("notes", models.TextField(blank=True, default="")),
                ("published", models.BooleanField(default=True)),
                (
                    "published_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-published_at", "-version_code"],
            },
        ),
    ]
