# Generated by Django 4.2.30 on 2026-09-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bravepos", "0041_apprelease"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="crm_branch_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="branch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("crm_branch_id__isnull", False)),
                fields=("crm_branch_id",),
                name="branch_crm_id_unique_when_set",
            ),
        ),
    ]
