# Generated by Django 4.2.30 on 2026-09-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bravepos", "0042_branch_crm_link"),
    ]

    operations = [
        # Off everywhere on the way in: the rollout is one branch at a time,
        # ticked in the backoffice, and this migration must not switch loyalty
        # on at a shop that is already trading.
        migrations.AddField(
            model_name="branch",
            name="crm_loyalty_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="crm_order_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
