# Generated by Django 4.2.30 on 2026-09-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bravepos", "0043_crm_loyalty"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerMergeBackup",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                ("payload", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
