# Generated by Django 4.2.30 on 2026-09-28 05:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("bravepos", "0052_global_suggestion_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="discount_types_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="discount_label",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="discount_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="DiscountType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[("percent", "Percentage"), ("fixed", "Fixed amount")],
                        default="percent",
                        max_length=8,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("all_products", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discount_types",
                        to="bravepos.branch",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="discount_types", to="bravepos.product"
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["branch"], name="bravepos_di_branch__6ebaa6_idx"
                    )
                ],
            },
        ),
    ]
