# Generated by Django 4.2.30 on 2026-09-29 04:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("bravepos", "0054_discount_type_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="discounttype",
            name="free_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="free_with_discount_types",
                to="bravepos.product",
            ),
        ),
        migrations.AddField(
            model_name="discounttype",
            name="free_qty",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="discounttype",
            name="applies_to",
            field=models.CharField(
                choices=[
                    ("all", "All products"),
                    ("products", "Selected products"),
                    ("categories", "Selected categories"),
                    ("combo", "Combination"),
                ],
                default="all",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="discounttype",
            name="kind",
            field=models.CharField(
                choices=[
                    ("percent", "Percentage"),
                    ("fixed", "Fixed amount"),
                    ("free", "Free item"),
                ],
                default="percent",
                max_length=8,
            ),
        ),
        migrations.CreateModel(
            name="DiscountCondition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("min_qty", models.PositiveIntegerField(default=1)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="bravepos.category",
                    ),
                ),
                (
                    "discount_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="bravepos.discounttype",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="bravepos.product",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
    ]
