# Generated by Django 4.2.30 on 2026-09-29 05:13

from django.db import migrations, models


def number_existing(apps, schema_editor):
    """Give promotions made before IDs existed PR-0001… in creation order."""
    DiscountType = apps.get_model("bravepos", "DiscountType")
    for n, d in enumerate(DiscountType.objects.order_by("created_at", "id"), start=1):
        d.code = f"PR-{n:04d}"
        d.save(update_fields=["code"])


class Migration(migrations.Migration):

    dependencies = [
        ("bravepos", "0055_discount_combos_and_free_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="discounttype",
            name="code",
            field=models.CharField(
                blank=True, editable=False, max_length=16, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="discounttype",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discounttype",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(number_existing, migrations.RunPython.noop),
    ]
