# Generated by Django 4.2.30 on 2026-09-29 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bravepos", "0056_discount_promotion_period"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discounttype",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="discounttype",
            name="sort_order",
        ),
    ]
