# Generated by Django 4.2.30 on 2026-09-29 05:49

from django.db import migrations, models


def own_groups(apps, schema_editor):
    """Every existing promotion is its own group until it is synced."""
    DiscountType = apps.get_model("bravepos", "DiscountType")
    for d in DiscountType.objects.filter(group_id__isnull=True):
        d.group_id = d.id
        d.save(update_fields=["group_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("bravepos", "0057_discount_type_drop_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="discounttype",
            name="group_id",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.RunPython(own_groups, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="discounttype",
            name="code",
            field=models.CharField(
                blank=True, editable=False, max_length=16, null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="discounttype",
            constraint=models.UniqueConstraint(
                fields=("code", "branch"), name="discounttype_code_per_branch"
            ),
        ),
        migrations.AddConstraint(
            model_name="discounttype",
            constraint=models.UniqueConstraint(
                fields=("group_id", "branch"), name="discounttype_one_copy_per_branch"
            ),
        ),
    ]
