# Generated by Django 4.2.30 on 2026-09-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bravepos", "0058_discount_type_branch_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="discounttype",
            name="combo_match",
            field=models.CharField(
                choices=[("all", "All of these together"), ("any", "Any one of these")],
                default="all",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="discounttype",
            name="max_discount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="discounttype",
            name="min_order_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
