# Generated by Django 4.2.30 on 2026-09-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bravepos", "0059_discount_min_order_max_discount_or"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="shelf_life",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
