# Generated by Django 4.2.30 on 2026-09-29 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bravepos", "0060_product_shelf_life"),
    ]

    operations = [
        migrations.AddField(
            model_name="discounttype",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="bravepos.staff",
            ),
        ),
        migrations.AddField(
            model_name="discounttype",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="bravepos.staff",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="discount_code",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="discount_logic",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="is_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="sku",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
