# Generated by Django 4.2.30 on 2026-09-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bravepos', '0061_promotion_audit_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('cashier', 'Cashier'), ('viewer', 'Viewer')], default='cashier', max_length=16),
        ),
    ]
