# Generated by Django 4.2.30 on 2026-09-30 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bravepos', '0062_staff_viewer_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='discounttype',
            name='free_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_with_discount_types', to='bravepos.category'),
        ),
    ]
